from config_models import (
    AppConfig, ComputeEnvConfig, StateMachineConfig,
    BatchingStageConfig, BatchTaskJobDefConfig, StorageConfig,
    LoggingConfig, LambdaConfig, IngestStageConfig, UploadConfig,
    DLQOpsConfig, SQSConfig, DatasetConfig
)

CONFIG = AppConfig(
    app_name="cvdmsv1",
    logging=LoggingConfig(
        transform_lambda_path="workers/lambdas/logging",
        transform_lambda_duration_sec=60,
        transform_lambda_memory_size=256,
        firehose_interval_in_seconds=60,
        firehose_size_in_m_bs=64
    ),
    storage=StorageConfig(
        ddl_lambda_path="workers/lambdas/storage/iceberg_ddl",
        delete_db_lambda_path="workers/lambdas/storage",
        provider_ddl_lambda_path="workers/lambdas/storage",
        provider_cleanup_lambda_path = "workers/lambdas/storage"
    ),
    upload=UploadConfig(
        upload_state_machine=StateMachineConfig(duration_hours=2),
        kickoff_lambda=LambdaConfig(
            path="workers/lambdas/upload",
            handler="kickoff_upload.handler",
            memory_size=1024,
            timeout_sec=500
        ),
        compute_env=ComputeEnvConfig(
            minv_cpus=0,
            maxv_cpus=64,
            instance_types=["m5.large", "m5.xlarge", "m5.2xlarge"]
        ),
        dlq_ops=DLQOpsConfig(
            dlq_processor=LambdaConfig(
                    path="workers/lambdas/upload",
                    handler="dlq_processor_upload.handler",
                    memory_size=512,
                    timeout_sec=900
                ),
            sqs_queue=SQSConfig(
                    retention_period_days=14,
                    visibility_timeout_minutes=15
            )
        ),
        events_queue=SQSConfig(
                    retention_period_days=4,
                    visibility_timeout_minutes=15
        ),
        validation=BatchingStageConfig(
            file_batching=LambdaConfig(
                path="workers/lambdas/upload/file_batching",
                handler="validation.handler",
                memory_size=1024,
                timeout_sec=900
            ),
            map_max_concurrency=7,
            batch_task_job_def=BatchTaskJobDefConfig(
                vcpus=1,
                memory_limit_mib=2048,
                directory="workers",
                file="batch_jobs/upload/validation/Dockerfile"
            )
        ),
        deduplication=BatchingStageConfig(
            file_batching=LambdaConfig(
                path="workers/lambdas/upload/file_batching",
                handler="deduplication.handler",
                memory_size=1024,
                timeout_sec=900
            ),
            map_max_concurrency=7,
            batch_task_job_def=BatchTaskJobDefConfig(
                vcpus=1,
                memory_limit_mib=2048,
                directory="workers",
                file="batch_jobs/upload/deduplication/Dockerfile"
            )
        ),
        registration=BatchingStageConfig(
            file_batching=LambdaConfig(
                path="workers/lambdas/upload/file_batching",
                handler="registration.handler",
                memory_size=1024,
                timeout_sec=900
            ),
            map_max_concurrency=7,
            batch_task_job_def=BatchTaskJobDefConfig(
                vcpus=2,
                memory_limit_mib=4096,
                directory="workers",
                file="batch_jobs/upload/registration/Dockerfile"
            )
        ),
        validation_ingest=IngestStageConfig(
            pre_ingest_lambda=LambdaConfig(
                path="workers/lambdas/upload/ingest/validation",
                handler="validation_pre.handler",
                memory_size=1024,
                timeout_sec=900
            ),
            map_ingest_lambda=LambdaConfig(
                path="workers/lambdas/upload/ingest/validation",
                handler="validation_map.handler",
                memory_size=4096,
                timeout_sec=900
            ),
            map_max_concurrency=10, # max 40
            post_ingest_lambda=LambdaConfig(
                path="workers/lambdas/upload/ingest/validation",
                handler="validation_post.handler",
                memory_size=1024,
                timeout_sec=900
            )
        ),
        deduplication_ingest=IngestStageConfig(
            pre_ingest_lambda=LambdaConfig(
                path="workers/lambdas/upload/ingest/deduplication",
                handler="deduplication_pre.handler",
                memory_size=1024,
                timeout_sec=900
            ),
            map_ingest_lambda=LambdaConfig(
                path="workers/lambdas/upload/ingest/deduplication",
                handler="deduplication_map.handler",
                memory_size=4096,
                timeout_sec=900
            ),
            map_max_concurrency=10,
            post_ingest_lambda=LambdaConfig(
                path="workers/lambdas/upload/ingest/deduplication",
                handler="deduplication_post.handler",
                memory_size=1024,
                timeout_sec=900
            )
        ),
        registration_ingest=IngestStageConfig(
            pre_ingest_lambda=LambdaConfig(
                path="workers/lambdas/upload/ingest/registration",
                handler="registration_pre.handler",
                memory_size=1024,
                timeout_sec=900
            ),
            map_ingest_lambda=LambdaConfig(
                        path="workers/lambdas/upload/ingest/registration",
                        handler="registration_map.handler",
                        memory_size=4096,
                        timeout_sec=900
                    ),
            map_max_concurrency=10,
            post_ingest_lambda=LambdaConfig(
                path="workers/lambdas/upload/ingest/registration",
                handler="registration_post.handler",
                memory_size=1024,
                timeout_sec=900
            )
        ),
        cleanup_lambda=LambdaConfig(
            path="workers/lambdas/upload",
            handler="cleanup_upload.handler",
            memory_size=1024,
            timeout_sec=900
        )
    ),
    dataset=DatasetConfig(
            dataset_state_machine=StateMachineConfig(duration_hours=2),
            kickoff_lambda=LambdaConfig(
                path="workers/lambdas/dataset",
                handler="kickoff_dataset.handler",
                memory_size=1024,
                timeout_sec=900
            ),
            dlq_ops=DLQOpsConfig(
                dlq_processor=LambdaConfig(
                        path="workers/lambdas/dataset",
                        handler="dlq_processor_dataset.handler",
                        memory_size=512,
                        timeout_sec=600
                    ),
                sqs_queue=SQSConfig(
                        retention_period_days=14,
                        visibility_timeout_minutes=15
                )
            ),
            events_queue=SQSConfig(
                        retention_period_days=4,
                        visibility_timeout_minutes=15
            ),
            create_lambda=LambdaConfig(
                path="workers/lambdas/dataset",
                handler="create_dataset.handler",
                memory_size=1024,
                timeout_sec=900
            ),
            update_lambda=LambdaConfig(
                path="workers/lambdas/dataset",
                handler="update_dataset.handler",
                memory_size=1024,
                timeout_sec=900
            ),
            delete_lambda=LambdaConfig(
                path="workers/lambdas/dataset",
                handler="delete_dataset.handler",
                memory_size=1024,
                timeout_sec=900
            ),
            visualization_lambda=LambdaConfig(
                path="workers/lambdas/dataset",
                handler="visualize_dataset.handler",
                memory_size=1024,
                timeout_sec=900
            ),
            cleanup_lambda=LambdaConfig(
                path="workers/lambdas/dataset",
                handler="cleanup_dataset.handler",
                memory_size=1024,
                timeout_sec=500
            )
        )
)